# -*- mode: sh -*-
#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

#export ALTERNATE_EDITOR=''
#export EDITOR='emacsclient -t'
#export VISUAL='emacsclient -t'
export EDITOR='nvim'
export VISUAL='nvim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi


# Paths
#

export PATH="$HOME/Library/Python/3.5/bin:$PATH"

# Drupal Console
export PATH="/Projects/Personal/DrupalConsole/bin:$PATH"


# phpbrew
[[ -s "${HOME}/.phpbrew/bashrc" ]] && source "$HOME/.phpbrew/bashrc"

# Executables installed via Composer
export PATH="$HOME/.composer/vendor/bin:$PATH"

# Rust executables
export PATH="$HOME/.cargo/bin:$PATH"

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#
#
# Set TMPDIR if the variable is not set/empty or the directory doesn't exist
if [[ -z "${TMPDIR}" ]]; then
  export TMPDIR="/tmp/zsh-${UID}"
fi

if [[ ! -d "${TMPDIR}" ]]; then
  mkdir -m 700 "${TMPDIR}"
fi

TMPPREFIX="${TMPDIR%/}/zsh"

# custom executables
export PATH="$HOME/.dotfiles/bin:$HOME/.local/bin:$PATH"

export VAGRANT_I_KNOW_WHAT_IM_DOING_PLEASE_BE_QUIET=true
export PYENV_VIRTUALENV_DISABLE_PROMPT=1

export TILLER_NAMESPACE=tiller
export GO111MODULE=on
export GOROOT=/usr/local/opt/go/libexec
export GOPATH=$HOME/go
