#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='nvim'
export VISUAL='nvim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# rbenv
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# pyenv
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi

# Drupal Console
export PATH="/Projects/Personal/DrupalConsole/bin:$PATH"

# custom executables
export PATH="$HOME/.dotfiles/bin:$HOME/.local/bin:$PATH"

# phpbrew
[[ -s "${HOME}/.phpbrew/bashrc" ]] && source "$HOME/.phpbrew/bashrc"

# nvm
export NVM_DIR="/Users/bez/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"


function powerline_lib_path() {
  pip show powerline-status | grep Location | awk '{print $2}'
}

function src() {
  source $HOME/.zprofile
}

export POWERLINE_PATH=$(powerline_lib_path)/powerline
export HISTINGORE='clear:history'
export HISTORYCONTROL='ignoreboth'

# base16-shell
export BASE16_FLAVOR=${BASE16_FLAVOR:-"bright"}
export VIM_COLOR="base16-${BASE16_FLAVOR}"
export BACKGROUND=${BACKGROUND:-"dark"}

BASE16_SHELL="$HOME/TerminalMods/base16-shell/base16-${BASE16_FLAVOR}.${BACKGROUND}.sh"

# Avoid flickering in tmux
if [[ -z "$TMUX" ]]; then
  [[ -s $BASE16_SHELL ]] && source $BASE16_SHELL
fi

export ANSIBLE_NOCOWS=1

# tmuxinator
tmuxinator_version=$(gem list tmuxinator | grep tmuxinator | awk '{print $2}' | sed 's/(/-/' | sed 's/)//')
tmuxinator_dir=$(gem list tmuxinator -d | grep Installed | awk '{print $3}')
source $tmuxinator_dir/gems/tmuxinator$tmuxinator_version/completion/tmuxinator.zsh

alias hacksh='$SHELL | tr -u eauiobBgGsSlL 34U1088995577'
alias reinit-markers='/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -kill -seed'

# Drupal Console
source "$HOME/.console/console.rc" 2>/dev/null

export ANDROID_HOME=/usr/local/opt/android-sdk
export HOMEBREW_GITHUB_API_TOKEN=182130e66d4c5dfed0395ffd2509c601d74400af

alias vim=nvim
alias vi=nvim
alias quit=exit

function dark() {
  if [[ "$1" != "" ]]; then
    export BASE16_FLAVOR="$1"
  fi
  export POWERLINE_CONFIG_OVERRIDES=ext.tmux.colorscheme=default
  export BACKGROUND='dark' && src
}

function light() {
  if [[ "$1" != "" ]]; then
    export BASE16_FLAVOR="$1"
  fi
  export POWERLINE_CONFIG_OVERRIDES=ext.tmux.colorscheme=light
  export BACKGROUND="light" && src
}

# tmux variables
export TMUX_BORDER_FG=colour255
export TMUX_BORDER_BG=colour236
export TMUX_BORDER_FG_ACTIVE=colour160
export TMUX_BORDER_BG_ACTIVE=colour236

