#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

#export ZPLUG_HOME=/usr/local/opt/zplug
#[ -f $ZPLUG_HOME/init.zsh ] && source $ZPLUG_HOME/init.zsh || :
##zplug 'unixorn/tumult.plugin.zsh'
#zplug 'Tarrasch/zsh-bd'
#zplug load

export GREP_COLOR='1;37;41'
export FZF_DEFAULT_COMMAND="ag --hidden --skip-vcs-ignores --ignore .git -f -g \"\""
export FZF_DEFAULT_OPTS='
  --color=fg:7,bg:0,hl:1,bg+:18,fg+:5,hl+:1,info:8,prompt:5,pointer:2,marker:6,spinner:3,header:8
  --no-mouse --margin=0,0,0,1
  --prompt="› "
  --tabstop=2
  -1
'

# Will have to redefine $EDITOR because `tumult` might have overwritten it.
# export EDITOR=nvim

# Customize to your needs...

setopt NO_CLOBBER
#setopt AUTO_CD
setopt MULTIOS
setopt AUTO_PUSHD
setopt GLOB_COMPLETE
setopt PUSHD_MINUS
#setopt PUSHD_SILENT
setopt PUSHD_TO_HOME
setopt PUSHD_IGNORE_DUPS
setopt RM_STAR_WAIT

# Show trailing slash on directories on `ls`
alias ls="ls -GF"
bindkey "^r" history-incremental-search-backward

autoload -Uz surround
zle -N delete-surround surround
zle -N add-surround surround
zle -N change-surround surround
bindkey -a cs change-surround
bindkey -a ds delete-surround
bindkey -a ys add-surround
bindkey -M visual S add-surround
KEYTIMEOUT=1

tmux-register-lang-versions

fpath=(/usr/local/share/zsh-completions $fpath)

export TERM='xterm-256color'
export TMUX_CONFIG_DIR="$HOME/.dotfiles/tmux"

function src() {
  source $HOME/.dotfiles/zsh/.zprofile
}

#BASE16_SHELL=$HOME/.dotfiles/base16-shell/
#[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

function dark() {
  if [[ "$1" != "" ]]; then
    export BASE16_FLAVOR="$1"
  fi
  export POWERLINE_CONFIG_OVERRIDES=ext.tmux.colorscheme=default
  export TMUX_BORDER_FG_ACTIVE=colour42
  export TMUX_BORDER_FG=colour240
  export BACKGROUND='dark'
  export THEME_CHANGED=1
  export TMUX_BG="black"
}

function light() {
  if [[ "$1" != "" ]]; then
    export BASE16_FLAVOR="$1"
  fi
  export POWERLINE_CONFIG_OVERRIDES=ext.tmux.colorscheme=light
  export TMUX_BORDER_FG_ACTIVE=colour1
  export TMUX_BORDER_FG=colour248
  export BACKGROUND="light"
  export THEME_CHANGED=1
  export TMUX_BG="white"
}

if [[ -z "$THEME_CHANGED" ]]; then
  dark bright
fi

#export POWERLINE_PATH=$(powerline_lib_path)/powerline
export HISTINGORE='clear:history'
export HISTORYCONTROL='ignoreboth'


# base16-shell
export BASE16_FLAVOR=${BASE16_FLAVOR:-"bright"}
export VIM_COLOR="base16-${BASE16_FLAVOR}"
export BACKGROUND=${BACKGROUND:-"dark"}
#
#base16_$BASE16_FLAVOR
source $HOME/.dotfiles/zsh/colorscheme.zsh
if [ -z "$TMUX_PANE" ]; then
  base16 materia
fi

#BASE16_SHELL_VARIANT="$HOME/.dotfiles/base16-shell/base16-${BASE16_FLAVOR}.${BACKGROUND}.sh"
#export THEME_CHANGED=0
#
## Avoid flickering in tmux
#if [[ -z "$TMUX" ]]; then
#  [[ -s $BASE16_SHELL_VARIANT ]] && source $BASE16_SHELL_VARIANT
#fi

export ANSIBLE_NOCOWS=1

# tmuxinator
tmuxinator_version=$(gem list tmuxinator | grep tmuxinator | awk '{print $2}' | sed 's/(/-/' | sed 's/)//')
tmuxinator_dir=$(gem list tmuxinator -d | grep Installed | awk '{print $3}')
source $tmuxinator_dir/gems/tmuxinator$tmuxinator_version/completion/tmuxinator.zsh
#type compdef

alias hacksh='$SHELL | tr -u eauiobBgGsSlL 34U1088995577'
alias reinit-markers='/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -kill -seed'

# Drupal Console
#source "$HOME/.console/console.rc" 2>/dev/null

export ANDROID_HOME=/usr/local/opt/android-sdk
export HOMEBREW_GITHUB_API_TOKEN=182130e66d4c5dfed0395ffd2509c601d74400af

alias vim=nvim
alias vi=nvim
alias quit=exit
alias mux=tmuxinator

# tmux variables
#export TMUX_BORDER_FG=colour255
#export TMUX_BORDER_BG=colour236
#export TMUX_BORDER_BG_ACTIVE=colour236

alias ydl="youtube-dl"
nvimdiff="nvim -d"

# Open `HUD` tmux session when invoking the HUD terminal in iTerm via the
# global hotkey. Create the session if it isn't there yet.
if [[ -z "$TMUX_PANE" && "$ITERM_PROFILE" == "Hotkey Window" ]]; then
  mux HUD
fi

alias color-table="vim +XtermColorTable +only"

function csview() {
  cat "$1" | column -s, -t | less -#5 -SN 
}

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export NVM_DIR="/Users/bez/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm


function load-platformsh() {
  # Automatically added by Platform.sh CLI installer
  export PATH="/Users/bez/.platformsh/bin:$PATH"
  . '/Users/bez/.platformsh/shell-config.rc' 2>/dev/null
}

alias a='fasd -a'        # any
alias s='fasd -si'       # show / search / select
alias d='fasd -d'        # directory
alias f='fasd -f'        # file
alias sd='fasd -sid'     # interactive directory selection
alias sf='fasd -sif'     # interactive file selection
alias z='fasd_cd -d'     # cd, same functionality as j in autojump
alias zz='fasd_cd -d -i' # cd with interactive selection

gitroot() {
  while [ ! -d .git ]
  do
    cd ..
  done
}

alias gr='gitroot'

start-copy-server() {
  while true; do nc -l 4737 | pbcopy; done 2>&1 &
}

# http://stackoverflow.com/a/10744524/908451
function git-show-orig {
    git status -su | grep -e"\.orig$" | cut -f2 -d" "
}

# Inspired by:
# http://boredzo.org/blog/archives/2016-08-15/colorized-man-pages-understood-and-customized
man() {
	env \
		LESS_TERMCAP_md=$'\e[1;36m' \
		LESS_TERMCAP_me=$'\e[0m' \
		LESS_TERMCAP_se=$'\e[0m' \
		LESS_TERMCAP_so=$'\e[1;41;38;5;15m' \
		LESS_TERMCAP_ue=$'\e[0m' \
		LESS_TERMCAP_us=$'\e[1;32m' \
			man "$@"
}

export GPG_TTY=$(tty)
